name: csilctl PR
description: "Validate commits and run the CLI test suite."
on:
  events:
    - pull_request_opened
    - pull_request_updated
  branches:
    - main
jobs:
  conventional-commits:
    job_file: conventional-commits.yaml

  test-cli:
    job_file: test-cli.yaml
    depends_on:
      - conventional-commits
